---
title: "Bibliography"
editor: visual
---

Here, we provide the references an collections used.

Collecions:

AMNH - American Museum of Natural History (New York, United States of America).

AMS - Australian Museum (Sydney, Australia).

BHMH - Universidade Federal de Minas Gerais, Museu de Historia Natural (Belo Horizonte, Brazil).

CEIOC - Instituto Oswaldo Cruz, Coleção Entomológica (Rio de Janeiro, Brazil).

CeNak - Center for Natural History of the University of Hamburg (Hamburg, Germany)

CERPE - Coleção Entomológica da Universidade Federal Rural de Pernambuco (Recife, Brazil).

CLEV - Cleveland Museum of Natural History (Cleveland, United States of America).

DARC – David A. Rider collection (Fargo, United States of America).

DZUP - Museu de Entomologia Padre Jesus Santiago Moure, Universidade Federal do Paraná (Curitiba, Brazil).

NMPC - National Museum (Prague, Czech Republic).

EMG - Entomologisches Museum Geyer, Insekten Dauerausstellung (Geyer, Germany).

FSCA - Florida State Collection of Arthropods (Gainesville, United States of America).

HNHM - Natural History Museum (Budapest, Hungary).

IAvH-E - Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (Villa de Leyva, Colombia).

ICN - Instituto de Ciencias Naturales, Universidad Nacional de Colombia (Bogotá, Colombia).

INHS - Illinois Natural History Survey (Champaign, United States of America).

INPA - Instituto Nacional de Pesquisas da Amazônia, Coleção Sistemática da Entomologia (Amazonas, Brazil).

MACN - Museo Argentina de Ciencias Naturales "Bernardino Rivadavia" (Buenos Aires, Argentina).

MCNZ - Museu de Ciências Naturais da Secretaria do Meio Ambiente e Infraestrutura (Porto Alegre, Brazil).

MCPM - Milwaukee City Public Museum (Milwaukee, United States of America).

MCTP - Museu de Ciencias da Pontificia Universidade Católica do Rio Grande do Sul (Porto Alegre, Brazil). 

MLPA - Universidad Nacional de La Plata, Museo de la Plata (La Plata, Argentina).

MNHN - Muséum National d'Histoire Naturelle (Paris, France).

MNRJ - Universidade do Rio Janeiro, Museu Nacional (Rio de Janeiro, Brazil).

MPUJ - Pontificia Universidad Javeriana, Museo Javeriano de Historia Natural, Laboratorio de Entomología (Bogota, Colombia). 

MZLS - Museé Zoologique (Lausanne, Switzerland).
MZSP - Museu de Zoologia da Universidade Federal de São Paulo (São Paulo, Brazil).


NHMUK - The Natural History Museum (London, United Kingdom).

NHRS - Naturhistoriska riksmuseet (Stockholm, Sweden).

OUMNH - Oxford University Museum of Natural History (Oxford, United Kingdom).

RBINS - Royal Belgian Institute of Natural Sciences (Brussels, Belgium).

RMCA - Musee Royal de l'Afrique Centrale (Tervurem, Belgium).

SDEI - Senckenberg Deutsches Entomologisches Institut (Müncheberg, Germany)

SIM - Staten Island Museum (Staten Island, United States of America).

STRI - Smithsonian Tropical Research Institute (Balboa, Panama). 

UFRG - Universidade Federal do Rio Grande do Sul (Porto Alegre, Brazil).

UFRJ - Universidade Federal do Rio de Janeiro (Rio de Janeiro, Brazil).

UNAB - Universidad Nacional, Facultad de Agronomía (Bogota, Colombia).

UMSP - University of Minnesota (St. Paul, United States of America).

USNM - National Museum of Natural History (Washington D.C., United States of America]

VMNH - Virginia Museum of Natural History (Martinsville, United States of America).

ZFMK - Zoologisches Forschungsmuseum "Alexander Koenig" (Bonn, Germany).

ZMHB - Museum für Naturkunde (Berlin, Germany).

ZMUC - University of Copenhagen, Zoological Museum (Copenhagen, Denmark).


References:

Ahmed N, Bajwa G. 2016. Hemiptera fauna of Haripur District, Pakistan. Pakistan Pak Entomol 38(1):43–45.

Arechavaleta M, Zurita N, Marrero MC, Martín JL (eds). 2005. Lista preliminar de Especies silvestres de Cabo Verde (Hongos, Plantas y Animales terrestres). Consejería de Medio Ambiente y Ordenación Territorial, Gobierno de Canarias.

Arismendi N, Thomas DB. 2003. Pentatomidae (Heteroptera) of Honduras: a checklist with description of a new ochlerine genus. Insecta Mundi 17(3-4):219–236.

Azim MN. 2011. Taxonomic survey of stink bugs (Heteroptera: Pentatomidae) of India. Halteres (3):1–10.

Barão KR, Ferrari A, Grazia J. 2013. Comparative morphology of selected characters of the Pentatomidae foreleg (Hemiptera, Heteroptera). Arthropod Structure & Development 42:425–435. doi:10.1016/j.asd.2013.04.004.

Barsagade DD, Gathalkar GB. 2016. First predation record of Canthecona furcellata (Wolff.)
(Hemiptera: Pentatomidae) on spinning stage silkworm Antheraea mylitta (Drury). Entomol Res 46:236–245. 

Becker M, Grazia-Vieira J. 1977. The Pentatomoidea [Heteroptera] collected in French Guiana by the expedition of the Muséum National D’Histoire Naturelle. Annls Soc ent Fr 13(1):53–67. 

Bhatnagar VR, Maurya RP, Brijwal L, Dobhal P, Suyal P, Singh NK. 2019. Study on variability among predatory stink bug, Eocanthecona furcellata (Wolff) (Hemiptera: Pentatomidae) population thriving in different agro-ecosystems of north-western Himalayas, India. J Entomol Zool Stud 7(3):726–736. 

Biswas B, Hassan ME, Chandra K, Kushwaha S, Mukherjee P. 2014. On an account of Pentatomoidea (Heteroptera: Hemiptera) from Chhattisgarh, India. Rec. zool. Surv. India 114(2): 211–231.

Bhojendra PB, Maurya RP, Brijwal L, Patwal H, Suyal P. 2020. Genetic variability in predatory stink bug Andrallus spinidens (F.) from north-west Himalaya. IndianJ Entomol 82:1–6. 

Brailovsky H, Mayorga C. 1994. Hemiptera-Heteroptera de México XLV. La subfamilia Asopinae (Pentatomidae), en la Estación de Biologia Tropical “Los Tuxtlas”, Veracruz, México. Anales Inst Biol Univ Nac Autón México, Ser Zool 65(1):33–43.

Brugnera R, Grazia J, Maynard A, Roca-Cusachs M. 2024. Delimiting Cantheconidea Schouteden 1907, with the description of a new genus (Heteroptera: Pentatomidae: Asopinae). Eur J Taxon 947: 191–215. doi:0.5852/ejt.2024.947.2629.

Brugnera R, Roell T, Campos LA, Grazia J. 2020a. Taxonomy of widespread Neotropical species of Podisus Herrich-Schäffer (Hemiptera: Pentatomidae: Asopinae): redescription of P. distinctus (Stål, 1860) and revalidation of P. fuscescens (Dallas, 1851). Zootaxa 4751(3): 546–562. doi: 10.11646/zootaxa.4751.3.7.

Bundy CS. 2012. An Annotated Checklist of the Stink Bugs (Heteroptera: Pentatomidae) of New Mexico. Grt Lakes Entomol. 45(3-4):196–209. doi:10.22543/0090-0222.2252

Cachan P. 1952. Les Pentatomidae de Madagascar (Hémipteres Hétéropteres). Mem Inst Sci Madagascar (E) 1(2):231–462.

Campos LA, Bertolin TBP, Teixeira RA, Martins FS. 2009. Diversidade de Pentatomoidea (Hemiptera, Heteroptera) em três fragmentos de Mata Atlântica no sul de Santa Catarina. Iheringia, Sér Zool 99(2):165–171.

Carpintero DL, de Biase S. 2019. Parajalloides, nuevo género de Asopinae (Hemiptera: Heteroptera: Pentatomidae) con dos nuevas especies de la Republica Argentina. Historia Natural, Tercera serie 9(2):183–199.

Casto de Elera RPFr. 1895. Catálogo sistemático de toda la fauna de Filipinas conocida hasta el presente, Volumen II, Articulados.Manila, Imprenta del colegio de Santo Tomás. doi:10.5962/bhl.title.58548.

Castro-Huertas V, Schwertner CF, Fernández F. 2015. New records of stink bugs (Hemiptera: Pentatomidae) from Colombia. Zootaxa 3973(3):553–566. doi:10.11646/zootaxa.3973.3.9.

Causton CE, Peck SB, Sinclair BJ, Roque-Albelo L, Hodgson CJ, Landry B. 2006. Alien Insects: Threats and Implications for Conservation of Galápagos Islands. Ann. Entomol. Soc. Am. 99(1):121–143.

Chakravalty S, Agnihotri M, Kumar L. 2016. Diversity of Insect fauna associated with pigeon pea and their succession in relation to crop phenology at Pantnagar, Uttarakhand. J Exp Zool India 19(1):1327–1332. 

Chandra K, Kushwaha S, Sambath S, Biswas B. 2012. Distribution and diversity of Hemiptera Fauna of Veerangana Durgavati Wildlife Sanctuary, Damoh, Madhya Pradesh (India). Biological Forum — An International Journal 4(1):68–74.

Chitgar MG, Hajizadeh J, Ghadamyari M, Karimi-Malati A, Hoda H. 2014. Sublethal effects of diazinon, fenitrothion and chlorpyrifos on the functional response of predatory bug,
Andrallus spinidens Fabricius (Hem.: Pentatomidae) in the laboratory conditions. J King Saud Univ Sci 26:113–118. doi:10.1016/j.jksus.2013.09.001.

Claver MA, Jaiswal P. 2013. Distribution and abundance of two predatory stink bugs
(Pentatomidae: Hemiptera) associated with rice field. A. J. .Entomol 6(1):33–36.

Coombs M, Khan SA. 1998. Population levels and natural enemies of Plautia affinis Dallas (Hemiptera: Pentatomidae) on raspberry, Rubus idaeus L., in south-eastern Queensland. Aust J Entomol 37:125–129. doi: 10.1111/j.1440-6055.1998.tb01559.x.

Das S, Roy S, Mukhopadhyay A. 2010. Diversity of arthropod natural enemies in the tea plantations of North Bengal with emphasis on their association with tea pests. Current Sci 99(10):1457–1463.

Dellapé PM, Martínez AP, Coscarón MdC. 2003. New distributional records for the asopine pentatomids in temperate South America. Zootaxa 318:1–16.

Díaz A, González C, Villalba V, Rodríguez G. 2000. Evaluación de insectos defoliadores y de sus enemigos naturales en plantaciones de palma de aceite (Elaeis guineensis Jacq.) del oriente de Venezuela. Palmas 21:195–200.

Distant W.L. 1892. A Naturalist in the Transvaal. R.H. Porter, London.
doi:10.5962/bhl.title.2478.

Distant WL. 1901. On the Rhynchota of the Congo region (Part I). Annales de la Société entomologique de Belgique 45:23–31.

Distant W.L. 1913. Percy Sladen Trust Expedition to the Seychelle Islands. No. IX. Rhynchota. Part I: Suborder Heteroptera. Trans Linn Soc Lond 16(2):139–191. doi:10.1111/j.1096-3642.1913.tb00115.x

Faúndez EI, Rider DA, Garcete-Barrett BR. 2018. New records of Alcaeorrhynchus grandis (Dallas, 1851) (Heteroptera: Pentatomidae) From Paraguay, with description of a teratological case. Bol Mus Nac Hist Nat Parag 22(1):27–29.

Gaikwad SM, Koli YJ, Bhawane GP. A note on three interesting Heteroptera from Kolhapur, Maharashtra, India. J Threat Taxa 9(9):10733–10737.

Gapon DA, Konstantinov FV. 2006. On the structure of the aedeagus of shield bugs (Heteroptera: Pentatomidae): III. Subfamily Asopinae. Entomol Rev 86(7):806–819.

Gathalkar GB, Barsagade DD. 2016. Parasites–predators: their occurrence and invasive impact on the tropical tasar silkworm Antheraea mylitta (Drury) in the zone of central India. Current Sci 111(10):1649–1657. doi:10.18520/cs/v111/i10/1649-1657.

Ghate HV, Pathak GP, Koli Y, Bhawane GP. 2012. First record of two Pentatomidae
bugs from Chandoli area, Kolhapur, Maharashtra, India. JoTT 4(4):2524–2528.

Gerstaecker A. 1892. Bestimmung der von Herrn. Dr. F. Stuhlmann in Ostafrika gesammelten Hemiptera. Jahrb Hamburg Wiss Anst 9(2):45–58.

Gillon D. 1972. Les Hémiptères Pentatomides d’un savane préforestière de Côte-d’Ivoire. Annales de l’Université d’Abidjan (E) 5(1):265–371.

Golding F.D. 1931. Further notes on the food-plants of Nigerian insects. Bulletin of Entomological Research 22 (2): 221–223. doi:10.1017/S0007485300035185.

Grande MLM, Rando JSS. 2018. Integrated pest control adopted by soybean and
corn farmers in Londrina, Paraná state, Brazil. Arq Inst Biol 85:1–4. doi:10.1590/1808-1657000242015.

Hesse AJ. 1925. 1. Contributions to a knowledge of the fauna of South-West Africa. IV. A list of the Heteropterous and Homopterous Hemiptera of South-West Africa. Ann S Afr Mus 23:1–190.

Hilgert C. 1908. Katalog der Collection von Erlanger in Nieder-Ingelheim a. Rh. R. Friedlaender & Sohn, Berlin. doi:10.5962/bhl.title.7511.

Hyodo D, Himuro C, Fujisaki K. 2014. Prey size affects the costs and benefits of group predation in nymphs of the predatory stink bug Andrallus spinidens (Heteroptera: Pentatomidae). J Ethol 32:173–178. doi: 10.1007/s10164-014-0406-4.

Jeannel R. 1913. Pentatomidae In: Voyage de Ch. Alluaud et R. Jeannel en Africa Orientale (1911–1912). Résultats scientifiques. Insectes Hémipteres. Librairie Albert Schulz, Paris.

Jung S, Kim J, Oh H, Heiss E. 2015. Type specimens of Heteroptera (Insecta: Hemiptera) collected from North Korea and adjacent regions deposited at Insect Collections of Chungnam National University (CNU) in Daejeon, Republic of Korea. Zootaxa 3981(3):397–404. doi:10.11646/zootaxa.3981.3.5.

Juscelino-Filho P, Zanuncio JC, Fragoso DB, Serrão JE, Lacerda MC. 2003. Biology of Brontocoris tabidus (Heteroptera: Pentatomidae) fed with Musca domestica (Diptera: Muscidae) larvae. Braz J Biol 63(3):463–468.

Kandhro R, Khatri I, Rustamani MA, Abro N. 2016. Some stink bugs (Heteroptera: Pentatomidae) from Tando Jam Sindh. Sci Int (Lahore) 28(1):187–189.

Kaur H, Semahagn BK. 2010. Meiotic behaviour of chromosomes in three predator
species of the subfamily Asopinae (Heteroptera: Pentatomidae). Comp Cytogenet 4(2): 133–139. 

Kaur H, Singh D, Suman D. 2012. Faunal diversity of terrestrial Heteroptera (Insecta: Hemiptera) in Punjab, India. J ent Res 36(2):177–181.

Kerzhner IM. 2005. Notes on nomenclature and distribution of some Palaearctic Pentatomidae (Heteroptera). Zoosyst Rossica 14:73–75.

Kirkaldy GW. 1909. Catalogue of the Hemiptera (Heteroptera) with biological and anatomical References, Lists of Foodplants and Parasites, etc. Vol. 1: Cimicidae. Felix L. Dames, Berlin.


Knight HH. 1952. Review of the genus Perillus with description of a new species. Ann Ent Soc Am 45:229–232.

Koch RL, Rider DA, Tinerella RP, Rich WA. 2014. Stink Bugs (Hemiptera: Heteroptera: Pentatomidae) of Minnesota: An annotated checklist and new state records. Gt Lakes Entomol 47(3-4):171–185. 

Khuong DD. 2005. Bổ sung một giống và 6 loài bọ xít ăn thịt thuộc phân họ Asopinae (Pentatomidae-Heteroptera) cho khu hệ Việt Nam. Tạp chí sinh học 27(1):18–20. 

Lee H, Kim J, Jung S. 2015. A new record of genus Eocanthecona Bergroth (Hemiptera: Heteroptera: Pentatomidae: Asopinae) from the Korean Peninsula. Korean J Appl Entomol 54(3):257–261. doi:10.5656/KSAE.2015.05.0.009

Lehmann G. 1922. Erster Beitrag zur Verbreitung afrikanischer Pentatomiden (Heteroptera). (VII. Heteropteren-Aufsatz.). Konowia 1:129–133.

Lenin EA, Rajan SJ. 2016. Biology of predatory bug Eocanthecona furcellata Wolff (Hemiptera: Pentatomidae) on Corcyra cephalonica Stainton. J Entomol Zool Stud 4(3):338–340.

Leston D. 1952. Notes on The Ethiopian Pentatomoidea (Hemiptera). - VI. Some insects in
the Hope Department, Oxford. Ann Mag Nat Hist 12(5):893–904. doi:10.1080/00222935208654367.

Lindberg H. 1958. Hemiptera Insularum Caboverdensium. Systematik, Ökologie und Verbreitung der Heteropteren und Cicadiden der Kapverdischen Inseln. Commentationes Biologicae 19(1):1–246.

Linnavuori R. 1976. A hemipterous material from Somalia. Boll Soc entom Ital 108(5–7): 123–130.

Linnavuori RE. 1982. Pentatomidae and Acanthosomatidae (Heteroptera) of Nigeria and the Ivory Coast, with remarks on species of the adjacent countries in West and Central Africa. Acta Zool Fenn 163:1–176.

Linnavuori RE. 1989. Heteroptera of Yemen and south Yemen. Acta Entomol Fenn 54:1–40.

Lodos N, Önder F. 1983. Contribution to the study on the Turkish Pentatomoidea (Heteroptera) Vi. Asopinae (Amyot &Serville) 1843. Türk Bit Kor 7: 221–230.
 
Lupoli R. 2019. First catalogue of the Asopinae (Hemiptera, Pentatomidae) from French Guiana. Zootaxa 4668(1):076–088. doi:10.11646/zootaxa.4668.1.4.

Magistrali IC, Costa EC, Machado LM, Nadai J. 2014. Novos registros de Asopinae (Pentatomidae) predadores de lagartas Nystalea nyseus (Cramer, 1775) (Lepidoptera: Notodontidae). Biotemas 27(2):209–212. doi:10.5007/2175-7925.2014v27n2p209.

Malaguido AB, Panizzi AR. 1998. Alcaeorrhynchus grandis (Dallas): An Eventual Predator of Chlosyne lacinia saundersii Doubleday & Hewitson on Sunflower in Northern Paraná State. An Soc Entomol Brasil 27(4):671–674.

Maldès JM, Pluot-Sigwalt D. 2004. Les Asopinae afrotropicaux et malgaches conservés au MNHN à Paris: Liste des spécimens types et des espèces représentées [Heteroptera: Pentatomidae]. Rev Fr Entomol 26(1):19–28.

Mamet JR 1957. A revised and annotated list of the Hemiptera (Heteroptera and Homoptera, excluding Sternorrhyncha) of Mauritius. Mauritius Inst Bull 5(2):31–81.

Mancini C. 1937. Resultati scientifici delle missioni del Prof. G. Paoli in Somalia. Emitteri - Nota I. Boll Soc entom Ital 69(1–2):40–44.

Mathew K. 1986. On a collection of Pentatomidae (Hemiptera) from Silent Valley Kerala, India. Rec zool Surv India 84(1-4):35–47. 

McKay F, Dellapé G, Dyer K, Wheeler GS. 2019. New record of Brontocoris tabidus (Hemiptera: Pentatomidae) attacking larvae of Heteroperreyia hubrichi (Hymenoptera: Pergidae). Rev Soc Entomol Arg 78(2):22-25. 

Melo MC, Dellapé G, Oliveira L, Varela PS, Montemayor SI, Dellapé PM. 2017. Diversity of true bugs from Iguazú National Park, Argentina. Check List 13(5):479–511. doi:10.15560/13.5.479.

Menezes CWG, Soares MA, Assis Júnior SL, Menezes SJMC, dos Santos JB, Zanuncio JC. Brontocoris tabidus (Heteroptera: Pentatomidae) preying on Podalia walkeri (Lepidoptera: Megalopygidae) on eucalypt plants in Brazil. Fla Entomol 96(1):261–263. doi:10.1653/024.096.0141.

Mensah RK. 2002. Development of an integrated pest management programme for cotton. Part 1: Establishing and utililizing natural enemies. Int J Pest Manag 48(2):87–94 doi:10.1080/09670870110095377.

Miyamoto S. 1965. Heteropterous Insects of Formosa collected by Dr. Shirozu and others, 1961. Spec Bull Lep Soc Jap 1:227–238.

Mohaghegh J. 2008. New records of the predatory stinkbugs (Het.: Pentatomidae: Asopinae)
from Iran. J Entomol Soc Iran 27(2):1–4.

O’Donnell JA, Schaefer CW. 2012. Annotated Checklist of the Pentatomidae (Heteroptera) 
of Connecticut. Gt Lakes Entomol 45(3-4):220–234.

Ortega-León G. 1997. Distribuición de la subfamilia Asopinae (Hemiptera: Heteroptera: Pentatomidae) para México. Anales Inst Biol Univ Nac Autón México, Ser Zool 68(1):53–89.

Pal A, Dash S, Khanra S, Gupta D. Diversity and distribution of predatory stink bugs from India and their role in insect pest management (Hemiptera: Heteroptera: Pentatomidae: Asopinae). Int J Zool Appl Biosci 8(2):29–35. doi:10.55126/ijzab.2023.v08.i02.004.

Pan M, Zhang H, Zhang L, Chen H. 2019. Effects of Starvation and Prey Availability on Predation and Dispersal of an Omnivorous Predator Arma chinensis Fallou. J Insect Behav 32:134–144.

Perez-Gelabert DE, Thomas DB. 2005. Stink bugs (Heteroptera: Pentatomidae) of the island of Hispaniola, with seven new species from the Dominican Republic. Boletín de la SEA 37:319−352.

Pezzini DT, Haag M, Walker J, Koch RL. 2018. Pentatomidae (Hemiptera: Heteroptera:
Pentatomidae) captured on purple prism traps deployed for detection of emerald ash borer (Agrilus planipennis) (Coleoptera: Buprestidae) in Minnesota. Gt Lakes Entomol 51(1-2):10–17.

Phillips KA. 1983. A taxonomic revision of the Neacrtic species of Apateticus Dallas and Podisus Herrich-Schaeffer (Heteroptera: Pentatomidae: Asopinae). Doctoral thesis. Oregon State University, USA, 278p.

Reid CAM, Beatson M, Hasenpusch J. 2009. The morphology and biology of Pterodunga mirabile Daccordi, an unusual subsocial Chrysomeline (Coleoptera: Chrysomelidae). J Nat Hist 43(7–8):373–398.

Ribeiro RC, Lemos WP, Bernardino AS, Buecke J, Müller AA. 2010. Primeira ocorrência de Alcaeorrhynchus grandis (Dallas) (Hemiptera:Pentatomidae) predando lagartas desfolhadoras do dendezeiro no estado do Pará. Neotrop Entomol 39(1):131–132.

Rider DA. 2012. The Heteroptera (Hemiptera) of North Dakota I: Pentatomomorpha: Pentatomoidea. Gt Lakes Entomol 45(3-4):312–381.

Rider DA, Zheng L. 2002. Checklist and nomenclatural notes on the chinese Pentatomidae (Heteroptera) I. Asopinae. Entomotaxonomia 24(2):107–115.

Roca-Cusachs M, Kim J, Lee H, Lee G-A, Jung S. 2018. Revision of genus Stilbotes Stål (Hemiptera: Pentatomoidea: Pentatomidae: Asopinae) with description of a new species. Zootaxa 4425(2):385–392. doi: 10.11646/zootaxa.4425.2.12.

Roca-Cusachs M, Kim J, Kim K-H, Lee S-G, Jung S. 2019. Spockia tagala gen. and sp. nov. a new monotypic genus of Asopinae (Hemiptera: Heteroptera: Pentatomidae) from the Philippines. Zootaxa 4613(1):181–186. doi: 10.11646/zootaxa.4613.1.11.

Roell TR, Brugnera R, Lemaître VA. 2021a. Lost and found—Discovery of the presumed lost type of Arma pallipes Dallas, new synonymy and description of two new species of Podisus Herrich-Schäffer (Hemiptera: Pentatomidae: Asopinae). Zootaxa 4958(1):570–584. doi:10.11646/zootaxa.4958.1.33.

Roell TR, Bruckner H, Duarte M. 2021b. Tylospilus gaumeri (Distant, 1889) comb.n. (Insecta: Hemiptera: Pentatomidae): new combination and revised status. Ann Naturhist Mus Wien B 123: 263–275.

Roell TR, Lemaître VA, Webb MD. 2019. Revision of the African shieldbug genus Afrius Stål, 1870 (Hemiptera: Heteroptera: Pentatomidae: Asopinae). Eur J Taxon 520:1–44. doi:10.5852/ejt.2019.520.

Roell TR, Lemaître VA, Webb MD, Campos LA. 2023. An annotated and illustrated Type Catalogue of the predacious Shieldbugs (Hemiptera: Heteroptera: Pentatomidae: Asopinae) in the Collection of the Natural History Museum, London. Zootaxa 5232(1):001–105. doi: 10.11646/zootaxa.5232.1.1.

Ruckes H. 1963. Insects of Micronesia: Heteroptera: Pentatomoidea. Insects of Micronesia 7(7):307–356.

Salini S. 2016. Redescription of a predatory stink bug, Amyotea malabarica (Fabricius, 1775) (Hemiptera: Pentatomidae: Asopinae). J Biol Control 30(4):1–8. doi:10.18311/jbc/2016/15599.

Salini S, Viraktamath, CA. 2015. Genera of Pentatomidae (Hemiptera: Pentatomoidea) from south India-an illustrated key to genera and checklist of species. Zootaxa 3924(1):1–76. doi: 10.11646/zootaxa.3924.1.1.

Sampaio VG, Roell T, Campos LA. 2023. Revision of Heteroscelis Latreille, 1829 (Heteroptera: Pentatomidae: Asopinae) with the description of a new species from Colombia. Zootaxa 5278(3):401–438. doi:10.11646/zootaxa.5278.3.1.

Santos G, Bastardo RH. 2012. Nuevos registros de hiedevivos (Insecta: Hemiptera: Pentatomidae) para la República Dominicana y La Hispaniola, incluyendo el nuevo hallazgo
de Piezosternum subulatum (Thunberg, 1783). Novitates Caribaea 5:120-123.

Schaefer PW, Hedlund RC, Ikebe K. 1979. Dinorhynchus dybowskyi, an arboreal predator of forest insects including the gypsy moth, in Hokkaido, Japan, and laboratory rearing success. Environ Entomol 8:744-751.

Schouteden H. 1905. Rhynchota Aethiopica II. Arminae et Tessaratominae. Faune entomologique de l’Afrique tropicale. Ann Mus Congo Zool 3(1):133–277.

Schouteden H. 1909. Catalogues raisonnés de la faune entomologique du Congo Belge. I. Hémiptères-Hétéroptères, Fam. Pentatomidae. Ann Mus Congo Zool (3) 2(1):1–85.

Schouteden H. 1910. Wissenschaftliche Ergebnisse der schwedischen zoologischen Expedition nach dem Kilimandjaro, dem Meru und den Umgebenden Massaisteppen Deutsch-Ostafrikas 1905-1906 unter Leitung von Prof. Dr. Yngve Sjöstedt. 12. Hemiptera. 6. Pentatomidae. In: Sjöstedts Kilimandjaro-Meru Expedition 12:73–96. Stockholm.

Schouteden H. 1913. Pentatomides de la Guinée Portugaise. Rev Zool Afric 3(2):324–328.

Schouteden H. 1963. Pentatomides de la Côte d’Ivoire I. Rev Zool Bot Africaines 68(3–4): 397–402.

Schouteden H. 1964. Pentatomides de la Côte d’Ivoire II. Zool Bot Africaines 70(1–2):92–95.

Schouteden H. 1972. Pentatomidae. Exploration du Parc National de l’Upemba – Mission G.F. de Witte 72(3):83–113.

Segarra-Carmona AE, Franqui RA, Pérez-Martínez H, Morales-Grajales A. 2015. New records for stink bugs (Heteroptera: Pentatomidae) in Puerto Rico. J Agric Univ PR 99(2):167–178.

Sharma AK, Mandloi R, Bhowmick AK, Thakur AS. 2019. Study on biodiversity of phototactic hexapod fauna by light trap in soybean (Glycine max L.) ecosystem. J Entomol Zool Stud 7(2):641–646.

Shestakov LS. 2008. Studies of Vibratory Signals in Pentatomid Bugs (Heteroptera, Asopinae) from European Russia. Entomol Rev 88(1):20–25.

Sites RW, Simpson KR, Wood DL. 2012. The Stink Bugs (Hemiptera: Heteroptera:
Pentatomidae) of Missouri. Grt Lakes Entomol 45(3-4): 134–163.

Sousa KKA, da Silva NNP, Querino RB. 2016. Levantamento populacional de Pentatomidae em feijão-caupi. Anais da II Jornada Científica da Embrapa Meio-Norte, Teresina,
PI, 13 a 14 de setembro de 2016. – Teresina, 126 p: 6–9.

Srikumar KK, Salini S, Smitha S, Kumar BS, Radhakrishnan B. 2018. Taxonomy, bionomics and predatory potential of Eocanthecona concinna (Walker) (Hemiptera: Pentatomidae: Asopinae). J Biol Control 32(2):81-86. doi:10.18311/jbc/2018/18213.

Stål C. 1870. Enumeratio Hemipterorum. Bidrag till en förteckning öfver alla hittills kända Hemiptera, jemte systematiska meddelanden. Kongl Vetensk Acad Handl 9(1):1–232. doi:10.5962/bhl.title.12549.

Swanson DR. 2012. An Updated Synopsis of the Pentatomoidea (Heteroptera) of Michigan. Gt Lakes Entomol 45(3-4):263–312.

Tanco J. 2018. Nuevas citas de Asopinae Amyot & Serville, 1843 para la Península
Ibérica (Hemiptera: Heteroptera: Pentatomidae). Revista gaditana de Entomología 9(1):85–91.

Thomas DB. 1994. Taxonomic synopsis of the Old World asopine genera Heteroptera: Pentatomidae). Insecta Mundi 8:145–211.

Ullah S, Ahmad H, Rafi MA. 2017. Taxonomy of Superfamily Pentatomoidea (Hemiptera: Heteroptera) from Swat-Pakistan. Journal of Entomology and Zoology Studies 5(1):725–731.

Usinger RL. 1941. The Genus Oechalia (Pentatomidae, Hemiptera). Proc Haw Ent Soc 11(1):59–93.

Usinger RL. 1942. A New Species of Oechalia from Oahu (Pentatomidae, Hemiptera). Proc Haw Ent Soc 11(2):217–218.

Villiers A. 1949. Mission P.L. Dekeyser et A. Villiers en Guinée et Côte-d’Ivoire (1946). Insectes (Première partie). Bull Inst Franç Afrique Noire, Catalogues 5:1–90.

Villiers A. 1952. Mission A. Villiers au Togo et au Dahomey (1950). XXI. Hémiptères. Bull Inst Franç Afrique Noire 14(4):1196–1213.

Villiers A. 1954. Contribution à l’étude du peuplement de la zone d’inondation du Niger (Mission G. Remaudière). X. - Hémiptères Hétéroptères. Bull Inst Franç Afrique Noire 16(1): 219–231.

Wagmare SH, Gaikwad SM. 2017. First record of the predatory stinkbug Eocanthecona concinna (Walker, 1867) (Pentatomfdae: Asopfnae) from India. J Threat Taxa 9(2):9870–9873.

Walker F. 1867. Catalogue of the specimens of heteropterous Hemiptera in the collection of the British Museum. Part II. Scutata. E. Newman, London, pp. 241–417.

Zack RS, Landolt PJ, Munyaneza JE. 2012. The Stink Bugs (Hemiptera: Heteroptera:
Pentatomidae) of Washington State. Gt Lakes Entomol 45(3-4):251–262.

Zanuncio JC, Torres JB, Sediyama CAZ, Pereira FF, Pastori PL, Wermelinger ED, Ramalho FS. 2009. Mortality of the defoliator Euselasia eucerus (Lepidoptera: Riodinidae) by biotic factors in an Eucalyptus urophylla plantation in Minas Gerais State, Brazil. An Acad Bras Ciênc 81(1):61–66.

Zhang J, Zhang X, Liu C, Meng L, Zhou Y. 2014. Fine structure and distribution of antennal sensilla of stink bug Arma chinensis (Heteroptera: Pentatomidae). Entomol Fenn. 25:186–199.

Zhao Q, Bu W-J, Liu G-Q. 2011. The genus Amyotea Ellenreider from China (Heteroptera, Pentatomidae). Acta Zootaxo Sinica. 36(4):950–955.

Zhao Q, Bu, W-J, Liu G-Q. 2016. The genus Cecyrina Walker, 1867, with the description of two new species (Hemiptera: Pentatomidae: Asopinae). Zootaxa 4114(3):309–319. doi:10.11646/zootaxa.4114.3.6.

Zhao Q, Liu G, Bu W. 2013. A review of the Chinese species of the genus Picromerus Amyot and Serville, with description of a new species (Hemiptera: Heteroptera: Pentatomidae: Asopinae). Zootaxa 3613(2):146–164. doi:10.11646/zootaxa.3613.2.3.

Zhao Q, Wei J, Bu W, Liu G, Zhang H. 2018a. Synonymize Arma chinensis as Arma custos based on morphological, molecular and geographical data. Zootaxa 4455(1):161–176. doi:10.11646/zootaxa.4455.1.7.

Zhao Q, Wang J, Wang M-Q, Cai B, Zhang H-F, Wei J-F. 2018. Complete mitochondrial genome of Dinorhynchus dybowskyi (Hemiptera: Pentatomidae: Asopinae) and phylogenetic analysis of Pentatomomorpha species. J Insect Sci 18(2):44; 1–12. doi:10.1093/jisesa/iey031.

Zibaee A, Hoda H, Fazeli-Dinan M. 2012. Role of proteases in extra-oral digestion of a predatory bug, Andrallus spinidens. J Insect Sci 12(51):1–17.






