---
title: "Raw Data"
format: html
editor: visual
---

```{r load data, message = FALSE, warning = FALSE, include = FALSE}
library(tidyverse)
library(leaflet)
library(htmlwidgets)
library(htmltools)
library(crosstalk)
library(bslib)
library(bsicons)
library(summarywidget)
library(reactable)
```

```{r}
#| echo: false
#| output: false

#READ DISTRBUTION DATA
asop <- read.csv("Asopinae_Analises_R_Preparado.csv", sep = ",")
asop <- asop %>%
  na.omit(asop) 
colnames(asop) <- c("Genus", "Species","Local_Label", "X_Longitude", "Y_Latitude", "Refs", "Country", "Continent", "Realm")

asop$X_Longitude <- as.numeric(asop$X_Longitude) 
asop$Y_Latitude <- as.numeric(asop$Y_Latitude)

row.names(asop) <- NULL


shared_asop <- SharedData$new(asop, group = "Asop")

share_species <- asop %>%
  select(Species) %>%
  unique() %>%
  SharedData$new(group = "Asop")
```

This is the current database of "Asopinae of the World". Here, you can look at the table data. It is the same table data available alongside the Distribution Map. Bellow it, you can also look at all the species in the database.

```{r}
#| echo: false

bscols(
  value_box(
    title = "Records",
    value = summarywidget(shared_asop),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#2f4538", fg = "#F3EEEA"),
    width = 0.1
  ),
  
    value_box(
    title = "Species",
    value = summarywidget(share_species),
    showcase = bsicons::bs_icon("search"),
    theme = value_box_theme(bg = "#2f4538", fg = "#F3EEEA"),
    width = 0.1
  )
  
)
```

```{r}
#| echo: false


library(fontawesome)

htmltools::browsable(
    tagList(
      tags$button(
        tagList(fontawesome::fa("download"), "Download as CSV"),
        onclick = "Reactable.downloadDataCSV('asop_table','Asopinae_Analises_R_Preparado.csv')"
      ),
    reactable(shared_asop,
              defaultColDef = colDef(
                  align = "left",
                  headerStyle = list(background = "#f7f7f8", fontSize = "11px"),  
                  style = list(fontSize = "11px") 
                ),
              columns = list(
            Genus = colDef(width = 50),
            Species = colDef(width = 80),
            Local_Label = colDef(width = 100),
            X_Longitude = colDef(width = 60),
            Y_Latitude = colDef(width = 60),
            Refs = colDef(width = 80),
            Country = colDef(width = 80),
            Continent = colDef(width = 80),
            Realm = colDef(width = 100)
          ),
              elementId = 'asop_table',
              highlight = TRUE,
              pagination = FALSE,
              height = 1000,
              width = "100%",
              style = list(fontSize = "10px"))
  )
)
  

```

## Species in the database

```{r gráfico n de registros}
#| echo: false
#| warning: false

regs <- read.csv("continents_countries.csv") %>%
  select(Species, Count, Conts, Number_Cont, Cntrs, Number_Cntr)

shared_plot <- SharedData$new(regs)


filter_select("Species", "Species", shared_plot, ~Species)
 




reactable(
  shared_plot,
  defaultColDef = colDef(
      align = "center",
      headerStyle = list(background = "#f7f7f8")
    ),
  columns = list(
      Species = colDef(name = "Species"),
      Count = colDef(name = "Number of Records"),
      Conts = colDef(name = "Continents Occuring"),
      Number_Cont = colDef(name = "Number of Continents Occuring"),
      Cntrs = colDef(name = "Countries Occuring"),
      Number_Cntr = colDef(name = "Number of Countries Occuring")
    ),
  highlight = TRUE,
  pagination = FALSE,
  height = 1000
)




```
